--
-- Файл сгенерирован с помощью SQLiteStudio v3.4.4 в Пн июл 8 19:54:57 2024
--
-- Использованная кодировка текста: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: CountryCodes
CREATE TABLE IF NOT EXISTS "CountryCodes" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_CountryCodes" PRIMARY KEY AUTOINCREMENT,
    "RussianName" TEXT NOT NULL,
    "EnglishName" TEXT NOT NULL,
    "LetterCode" TEXT NOT NULL,
    "ISO" INTEGER NOT NULL,
    "IsActive" INTEGER NOT NULL
);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (1, 'Абхазия', 'Abkhazia', 'AB', 895, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (2, 'Австралия', 'Australia', 'AU', 36, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (3, 'Австрия', 'Austria', 'AT', 40, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (4, 'Азербайджан', 'Azerbaijan', 'AZ', 31, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (5, 'Албания', 'Albania', 'AL', 8, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (6, 'Алжир', 'Algeria', 'DZ', 12, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (7, 'Американское Самоа', 'American Samoa', 'AS', 16, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (8, 'Ангилья', 'Anguilla', 'AI', 660, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (9, 'Ангола', 'Angola', 'AO', 24, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (10, 'Андорра', 'Andorra', 'AD', 20, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (11, 'Антарктида', 'Antarctica', 'AQ', 10, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (12, 'Антигуа и Барбуда', 'Antigua and Barbuda', 'AG', 28, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (13, 'Аргентина', 'Argentina', 'AR', 32, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (14, 'Армения', 'Armenia', 'AM', 51, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (15, 'Аруба', 'Aruba', 'AW', 533, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (16, 'Афганистан', 'Afghanistan', 'AF', 4, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (17, 'Багамы', 'Bahamas', 'BS', 44, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (18, 'Бангладеш', 'Bangladesh', 'BD', 50, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (19, 'Барбадос', 'Barbados', 'BB', 52, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (20, 'Бахрейн', 'Bahrain', 'BH', 48, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (21, 'Беларусь', 'Belarus', 'BY', 112, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (22, 'Белиз', 'Belize', 'BZ', 84, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (23, 'Бельгия', 'Belgium', 'BE', 56, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (24, 'Бенин', 'Benin', 'BJ', 204, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (25, 'Бермуды', 'Bermuda', 'BM', 60, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (26, 'Болгария', 'Bulgaria', 'BG', 100, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (27, 'Боливия, Многонациональное Государство', 'Bolivia, plurinational state of', 'BO', 68, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (28, 'Бонайре, Саба и Синт-Эстатиус', 'Bonaire, Sint Eustatius and Saba', 'BQ', 535, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (29, 'Босния и Герцеговина', 'Bosnia and Herzegovina', 'BA', 70, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (30, 'Ботсвана', 'Botswana', 'BW', 72, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (31, 'Бразилия', 'Brazil', 'BR', 76, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (32, 'Британская территория в Индийском океане', 'British Indian Ocean Territory', 'IO', 86, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (33, 'Бруней-Даруссалам', 'Brunei Darussalam', 'BN', 96, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (34, 'Буркина-Фасо', 'Burkina Faso', 'BF', 854, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (35, 'Бурунди', 'Burundi', 'BI', 108, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (36, 'Бутан', 'Bhutan', 'BT', 64, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (37, 'Вануату', 'Vanuatu', 'VU', 548, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (38, 'Венгрия', 'Hungary', 'HU', 348, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (39, 'Венесуэла Боливарианская Республика', 'Venezuela', 'VE', 862, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (40, 'Виргинские острова, Британские', 'Virgin Islands, British', 'VG', 92, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (41, 'Виргинские острова, США', 'Virgin Islands, U.S.', 'VI', 850, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (42, 'Вьетнам', 'Vietnam', 'VN', 704, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (43, 'Габон', 'Gabon', 'GA', 266, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (44, 'Гаити', 'Haiti', 'HT', 332, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (45, 'Гайана', 'Guyana', 'GY', 328, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (46, 'Гамбия', 'Gambia', 'GM', 270, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (47, 'Гана', 'Ghana', 'GH', 288, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (48, 'Гваделупа', 'Guadeloupe', 'GP', 312, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (49, 'Гватемала', 'Guatemala', 'GT', 320, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (50, 'Гвинея', 'Guinea', 'GN', 324, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (51, 'Гвинея-Бисау', 'Guinea-Bissau', 'GW', 624, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (52, 'Германия', 'Germany', 'DE', 276, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (53, 'Гернси', 'Guernsey', 'GG', 831, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (54, 'Гибралтар', 'Gibraltar', 'GI', 292, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (55, 'Гондурас', 'Honduras', 'HN', 340, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (56, 'Гонконг', 'Hong Kong', 'HK', 344, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (57, 'Гренада', 'Grenada', 'GD', 308, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (58, 'Гренландия', 'Greenland', 'GL', 304, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (59, 'Греция', 'Greece', 'GR', 300, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (60, 'Грузия', 'Georgia', 'GE', 268, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (61, 'Гуам', 'Guam', 'GU', 316, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (62, 'Дания', 'Denmark', 'DK', 208, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (63, 'Джерси', 'Jersey', 'JE', 832, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (64, 'Джибути', 'Djibouti', 'DJ', 262, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (65, 'Доминика', 'Dominica', 'DM', 212, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (66, 'Доминиканская Республика', 'Dominican Republic', 'DO', 214, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (67, 'Египет', 'Egypt', 'EG', 818, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (68, 'Замбия', 'Zambia', 'ZM', 894, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (69, 'Западная Сахара', 'Western Sahara', 'EH', 732, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (70, 'Зимбабве', 'Zimbabwe', 'ZW', 716, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (71, 'Израиль', 'Israel', 'IL', 376, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (72, 'Индия', 'India', 'IN', 356, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (73, 'Индонезия', 'Indonesia', 'ID', 360, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (74, 'Иордания', 'Jordan', 'JO', 400, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (75, 'Ирак', 'Iraq', 'IQ', 368, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (76, 'Иран, Исламская Республика', 'Iran, Islamic Republic of', 'IR', 364, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (77, 'Ирландия', 'Ireland', 'IE', 372, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (78, 'Исландия', 'Iceland', 'IS', 352, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (79, 'Испания', 'Spain', 'ES', 724, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (80, 'Италия', 'Italy', 'IT', 380, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (81, 'Йемен', 'Yemen', 'YE', 887, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (82, 'Кабо-Верде', 'Cape Verde', 'CV', 132, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (83, 'Казахстан', 'Kazakhstan', 'KZ', 398, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (84, 'Камбоджа', 'Cambodia', 'KH', 116, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (85, 'Камерун', 'Cameroon', 'CM', 120, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (86, 'Канада', 'Canada', 'CA', 124, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (87, 'Катар', 'Qatar', 'QA', 634, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (88, 'Кения', 'Kenya', 'KE', 404, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (89, 'Кипр', 'Cyprus', 'CY', 196, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (90, 'Киргизия', 'Kyrgyzstan', 'KG', 417, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (91, 'Кирибати', 'Kiribati', 'KI', 296, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (92, 'Китай', 'China', 'CN', 156, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (93, 'Кокосовые (Килинг) острова', 'Cocos (Keeling) Islands', 'CC', 166, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (94, 'Колумбия', 'Colombia', 'CO', 170, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (95, 'Коморы', 'Comoros', 'KM', 174, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (96, 'Конго', 'Congo', 'CG', 178, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (97, 'Конго, Демократическая Республика', 'Congo, Democratic Republic of the', 'CD', 180, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (98, 'Корея, Народно-Демократическая Республика', 'Korea, Democratic People''s republic of', 'KP', 408, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (99, 'Корея, Республика', 'Korea, Republic of', 'KR', 410, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (100, 'Коста-Рика', 'Costa Rica', 'CR', 188, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (101, 'Кот д''Ивуар', 'Cote d''Ivoire', 'CI', 384, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (102, 'Куба', 'Cuba', 'CU', 192, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (103, 'Кувейт', 'Kuwait', 'KW', 414, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (104, 'Кюрасао', 'Curaçao', 'CW', 531, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (105, 'Лаос', 'Lao People''s Democratic Republic', 'LA', 418, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (106, 'Латвия', 'Latvia', 'LV', 428, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (107, 'Лесото', 'Lesotho', 'LS', 426, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (108, 'Ливан', 'Lebanon', 'LB', 422, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (109, 'Ливийская Арабская Джамахирия', 'Libyan Arab Jamahiriya', 'LY', 434, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (110, 'Либерия', 'Liberia', 'LR', 430, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (111, 'Лихтенштейн', 'Liechtenstein', 'LI', 438, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (112, 'Литва', 'Lithuania', 'LT', 440, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (113, 'Люксембург', 'Luxembourg', 'LU', 442, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (114, 'Маврикий', 'Mauritius', 'MU', 480, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (115, 'Мавритания', 'Mauritania', 'MR', 478, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (116, 'Мадагаскар', 'Madagascar', 'MG', 450, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (117, 'Майотта', 'Mayotte', 'YT', 175, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (118, 'Макао', 'Macao', 'MO', 446, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (119, 'Малави', 'Malawi', 'MW', 454, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (120, 'Малайзия', 'Malaysia', 'MY', 458, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (121, 'Мали', 'Mali', 'ML', 466, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (122, 'Малые Тихоокеанские отдаленные острова Соединенных Штатов', 'United States Minor Outlying Islands', 'UM', 581, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (123, 'Мальдивы', 'Maldives', 'MV', 462, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (124, 'Мальта', 'Malta', 'MT', 470, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (125, 'Марокко', 'Morocco', 'MA', 504, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (126, 'Мартиника', 'Martinique', 'MQ', 474, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (127, 'Маршалловы острова', 'Marshall Islands', 'MH', 584, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (128, 'Мексика', 'Mexico', 'MX', 484, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (129, 'Микронезия, Федеративные Штаты', 'Micronesia, Federated States of', 'FM', 583, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (130, 'Мозамбик', 'Mozambique', 'MZ', 508, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (131, 'Молдова, Республика', 'Moldova', 'MD', 498, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (132, 'Монако', 'Monaco', 'MC', 492, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (133, 'Монголия', 'Mongolia', 'MN', 496, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (134, 'Монтсеррат', 'Montserrat', 'MS', 500, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (135, 'Мьянма', 'Burma', 'MM', 104, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (136, 'Намибия', 'Namibia', 'NA', 516, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (137, 'Науру', 'Nauru', 'NR', 520, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (138, 'Непал', 'Nepal', 'NP', 524, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (139, 'Нигер', 'Niger', 'NE', 562, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (140, 'Нигерия', 'Nigeria', 'NG', 566, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (141, 'Нидерланды', 'Netherlands', 'NL', 528, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (142, 'Никарагуа', 'Nicaragua', 'NI', 558, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (143, 'Ниуэ', 'Niue', 'NU', 570, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (144, 'Новая Зеландия', 'New Zealand', 'NZ', 554, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (145, 'Новая Каледония', 'New Caledonia', 'NC', 540, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (146, 'Норвегия', 'Norway', 'NO', 578, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (147, 'Объединенные Арабские Эмираты', 'United Arab Emirates', 'AE', 784, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (148, 'Оман', 'Oman', 'OM', 512, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (149, 'Остров Буве', 'Bouvet Island', 'BV', 74, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (150, 'Остров Мэн', 'Isle of Man', 'IM', 833, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (151, 'Остров Норфолк', 'Norfolk Island', 'NF', 574, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (152, 'Остров Рождества', 'Christmas Island', 'CX', 162, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (153, 'Остров Херд и острова Макдональд', 'Heard Island and McDonald Islands', 'HM', 334, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (154, 'Острова Кайман', 'Cayman Islands', 'KY', 136, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (155, 'Острова Кука', 'Cook Islands', 'CK', 184, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (156, 'Острова Теркс и Кайкос', 'Turks and Caicos Islands', 'TC', 796, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (157, 'Пакистан', 'Pakistan', 'PK', 586, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (158, 'Палау', 'Palau', 'PW', 585, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (159, 'Палестинская территория, оккупированная', 'Palestinian Territory, Occupied', 'PS', 275, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (160, 'Панама', 'Panama', 'PA', 591, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (161, 'Папский Престол (Государство &mdash; город Ватикан)', 'Holy See (Vatican City State)', 'VA', 336, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (162, 'Папуа-Новая Гвинея', 'Papua New Guinea', 'PG', 598, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (163, 'Парагвай', 'Paraguay', 'PY', 600, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (164, 'Перу', 'Peru', 'PE', 604, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (165, 'Питкерн', 'Pitcairn', 'PN', 612, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (166, 'Польша', 'Poland', 'PL', 616, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (167, 'Португалия', 'Portugal', 'PT', 620, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (168, 'Пуэрто-Рико', 'Puerto Rico', 'PR', 630, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (169, 'Республика Македония', 'Macedonia, The Former Yugoslav Republic Of', 'MK', 807, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (170, 'Реюньон', 'Reunion', 'RE', 638, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (171, 'Россия', 'Russian Federation', 'RU', 643, 1);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (172, 'Руанда', 'Rwanda', 'RW', 646, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (173, 'Румыния', 'Romania', 'RO', 642, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (174, 'Самоа', 'Samoa', 'WS', 882, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (175, 'Сан-Марино', 'San Marino', 'SM', 674, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (176, 'Сан-Томе и Принсипи', 'Sao Tome and Principe', 'ST', 678, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (177, 'Саудовская Аравия', 'Saudi Arabia', 'SA', 682, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (178, 'Святая Елена, Остров вознесения, Тристан-да-Кунья', 'Saint Helena, Ascension And Tristan Da Cunha', 'SH', 654, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (179, 'Северные Марианские острова', 'Northern Mariana Islands', 'MP', 580, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (180, 'Сен-Бартельми', 'Saint Barthélemy', 'BL', 652, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (181, 'Сен-Мартен', 'Saint Martin (French Part)', 'MF', 663, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (182, 'Сенегал', 'Senegal', 'SN', 686, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (183, 'Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', 'VC', 670, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (184, 'Сент-Китс и Невис', 'Saint Kitts and Nevis', 'KN', 659, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (185, 'Сент-Люсия', 'Saint Lucia', 'LC', 662, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (186, 'Сент-Пьер и Микелон', 'Saint Pierre and Miquelon', 'PM', 666, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (187, 'Сербия', 'Serbia', 'RS', 688, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (188, 'Сейшелы', 'Seychelles', 'SC', 690, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (189, 'Сингапур', 'Singapore', 'SG', 702, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (190, 'Синт-Мартен', 'Sint Maarten', 'SX', 534, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (191, 'Сирийская Арабская Республика', 'Syrian Arab Republic', 'SY', 760, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (192, 'Словакия', 'Slovakia', 'SK', 703, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (193, 'Словения', 'Slovenia', 'SI', 705, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (194, 'Соединенное Королевство', 'United Kingdom', 'GB', 826, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (195, 'Соединенные Штаты', 'United States', 'US', 840, 1);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (196, 'Соломоновы острова', 'Solomon Islands', 'SB', 90, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (197, 'Сомали', 'Somalia', 'SO', 706, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (198, 'Судан', 'Sudan', 'SD', 729, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (199, 'Суринам', 'Suriname', 'SR', 740, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (200, 'Сьерра-Леоне', 'Sierra Leone', 'SL', 694, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (201, 'Таджикистан', 'Tajikistan', 'TJ', 762, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (202, 'Таиланд', 'Thailand', 'TH', 764, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (203, 'Тайвань (Китай)', 'Taiwan, Province of China', 'TW', 158, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (204, 'Танзания, Объединенная Республика', 'Tanzania, United Republic Of', 'TZ', 834, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (205, 'Тимор-Лесте', 'Timor-Leste', 'TL', 626, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (206, 'Того', 'Togo', 'TG', 768, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (207, 'Токелау', 'Tokelau', 'TK', 772, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (208, 'Тонга', 'Tonga', 'TO', 776, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (209, 'Тринидад и Тобаго', 'Trinidad and Tobago', 'TT', 780, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (210, 'Тувалу', 'Tuvalu', 'TV', 798, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (211, 'Тунис', 'Tunisia', 'TN', 788, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (212, 'Туркмения', 'Turkmenistan', 'TM', 795, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (213, 'Турция', 'Turkey', 'TR', 792, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (214, 'Уганда', 'Uganda', 'UG', 800, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (215, 'Узбекистан', 'Uzbekistan', 'UZ', 860, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (216, 'Украина', 'Ukraine', 'UA', 804, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (217, 'Уоллис и Футуна', 'Wallis and Futuna', 'WF', 876, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (218, 'Уругвай', 'Uruguay', 'UY', 858, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (219, 'Фарерские острова', 'Faroe Islands', 'FO', 234, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (220, 'Фиджи', 'Fiji', 'FJ', 242, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (221, 'Филиппины', 'Philippines', 'PH', 608, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (222, 'Финляндия', 'Finland', 'FI', 246, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (223, 'Фолклендские острова (Мальвинские)', 'Falkland Islands (Malvinas)', 'FK', 238, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (224, 'Франция', 'France', 'FR', 250, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (225, 'Французская Гвиана', 'French Guiana', 'GF', 254, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (226, 'Французская Полинезия', 'French Polynesia', 'PF', 258, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (227, 'Французские Южные территории', 'French Southern Territories', 'TF', 260, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (228, 'Хорватия', 'Croatia', 'HR', 191, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (229, 'Центрально-Африканская Республика', 'Central African Republic', 'CF', 140, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (230, 'Чад', 'Chad', 'TD', 148, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (231, 'Черногория', 'Montenegro', 'ME', 499, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (232, 'Чешская Республика', 'Czech Republic', 'CZ', 203, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (233, 'Чили', 'Chile', 'CL', 152, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (234, 'Швейцария', 'Switzerland', 'CH', 756, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (235, 'Швеция', 'Sweden', 'SE', 752, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (236, 'Шпицберген и Ян Майен', 'Svalbard and Jan Mayen', 'SJ', 744, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (237, 'Шри-Ланка', 'Sri Lanka', 'LK', 144, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (238, 'Эквадор', 'Ecuador', 'EC', 218, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (239, 'Экваториальная Гвинея', 'Equatorial Guinea', 'GQ', 226, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (240, 'Эландские острова', 'Åland Islands', 'AX', 248, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (241, 'Эль-Сальвадор', 'El Salvador', 'SV', 222, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (242, 'Эритрея', 'Eritrea', 'ER', 232, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (243, 'Эсватини', 'Eswatini', 'SZ', 748, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (244, 'Эстония', 'Estonia', 'EE', 233, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (245, 'Эфиопия', 'Ethiopia', 'ET', 231, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (246, 'Южная Африка', 'South Africa', 'ZA', 710, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (247, 'Южная Джорджия и Южные Сандвичевы острова', 'South Georgia and the South Sandwich Islands', 'GS', 239, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (248, 'Южная Осетия', 'South Ossetia', 'OS', 896, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (249, 'Южный Судан', 'South Sudan', 'SS', 728, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (250, 'Ямайка', 'Jamaica', 'JM', 388, 0);
INSERT INTO CountryCodes (Id, RussianName, EnglishName, LetterCode, ISO, IsActive) VALUES (251, 'Япония', 'Japan', 'JP', 392, 0);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
